In [2]:
pip install pymongo

Collecting pymongo
  Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 32.4 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 30.0 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.17.0

In [3]:
import pandas
from pymongo import MongoClient

In [ ]:
client=MongoClient("CONNECTION URL")

In [ ]:
db = client["spiderdb"]

In [ ]:
collfilms=db["films"]

In [ ]:
data = list(collfilms.find())

In [5]:
df = pandas.DataFrame(data)
print(df)

     Name   Age       City   Salary Department
0  Prachi  21.0       Pune  25000.0         IT
1   Rahul   NaN     Nagpur      NaN         HR
2    None  24.0       None  30000.0       None
3    Amit  25.0     Mumbai  28000.0    Finance
4   Sneha   NaN      Delhi      NaN         IT
5    None  28.0    Chennai  35000.0       None
6   Rohan  30.0       None  40000.0      Sales
7   Kunal   NaN  Hyderabad      NaN  Marketing
8   Pooja  22.0       None  27000.0       None
9    None  27.0  Bangalore  32000.0         HR

In [6]:
# saves dataframe permanently in pickle (binary) format
df.to_pickle("filmsdata")

In [ ]:
print(pandas.isnull(df))

     _id  filmnm  releaseyr  genre  actor  imdbrating  main charter     id  \
0  False   False      False  False  False       False          True   True
1  False   False       True  False   True       False         False   True
2  False   False       True  False   True       False         False  False
3  False   False       True  False   True       False          True   True
4  False   False       True  False   True       False          True   True
5  False   False       True  False   True       False          True   True
6  False   False       True  False  False       False          True   True
7  False   False       True  False   True       False          True   True
8  False   False       True  False   True       False          True   True
9  False   False       True  False   True       False          True   True

   music  main char
0   True       True
1   True       True
2  False       True
3   True      False
4   True       True
5  False       True
6   True       True
7   True      False
8   True      False
9   True      False

In [7]:
# counts missing (NaN) values column-wise
df.isnull().sum()

Name          3
Age           3
City          3
Salary        3
Department    3
dtype: int64

**# counts total missing (NaN) values in the entire dataframe**

In [8]:
df.isnull().sum().sum()

np.int64(15)

**# dropna() removes rows that contain missing (NaN) values**

In [9]:
res=df.dropna()
print(res)

     Name   Age    City   Salary Department
0  Prachi  21.0    Pune  25000.0         IT
3    Amit  25.0  Mumbai  28000.0    Finance

**# remove cols with null value**

In [10]:
res=df.dropna(axis=1)
print(res)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
res=df.dropna(axis=1)    # remove cols which contians null
print(res)            # now in this case unkown values are print bcz we perform operation

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
data={
    'Name':['Mike','Virat','Surya',None,'Pat'],
    'Age' :[34, 37, None,56, None]
    }
df=pandas.DataFrame(data)
print(df)

    Name   Age
0   Mike  34.0
1  Virat  37.0
2  Surya   NaN
3   None  56.0
4    Pat   NaN

**# fills missing (NaN) values in Age column with average age**

In [16]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
print(df)

    Name        Age
0   Mike  34.000000
1  Virat  37.000000
2  Surya  42.333333
3   None  56.000000
4    Pat  42.333333

/tmp/ipykernel_4160/2591424001.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

**# convert above ages into int value**

In [17]:
df['Age'] = df['Age'].astype(int)
print(df)

    Name  Age
0   Mike   34
1  Virat   37
2  Surya   42
3   None   56
4    Pat   42

**QUE.1)**

In [18]:
data = {
    "Name": ['Will',None,'Mike','Amit'],
    "Age": [21, None, 24,None],
    "city": ['Pune','Nagpur',None,'Mumbai']
}

df = pandas.DataFrame(data)
print(df)

   Name   Age    city
0  Will  21.0    Pune
1  None   NaN  Nagpur
2  Mike  24.0    None
3  Amit   NaN  Mumbai

**# Check is null**

In [19]:
print(df.isnull())

    Name    Age   city
0  False  False  False
1   True   True  False
2  False  False   True
3  False   True  False

**# counts Total missing values**

In [21]:
print(df.isnull().sum().sum())

4

**# Drops rows where contains Nan value**

In [20]:
res = df.dropna()
print(res)

   Name   Age  city
0  Will  21.0  Pune


**# Fill missing values in city column with "Unknown"**

In [22]:
df['city'].fillna('unkown',inplace=True)
print(df)

   Name   Age    city
0  Will  21.0    Pune
1  None   NaN  Nagpur
2  Mike  24.0  unkown
3  Amit   NaN  Mumbai

/tmp/ipykernel_4160/2452682923.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].fillna('unkown',inplace=True)

**# Fill missing values in Age column using average age**

In [23]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
print(df)

   Name   Age    city
0  Will  21.0    Pune
1  None  22.5  Nagpur
2  Mike  24.0  unkown
3  Amit  22.5  Mumbai

/tmp/ipykernel_4160/2591424001.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

**# Convert Ages type into int but directly missing values support nahi karta isliye pahle Nan fill kro avgrages se**

In [24]:
df['Age'] = df['Age'].astype(int)
print(df)

   Name  Age    city
0  Will   21    Pune
1  None   22  Nagpur
2  Mike   24  unkown
3  Amit   22  Mumbai

**# Drop column where contains Nan value**

In [25]:
res = df.dropna(axis=1)
print(res)

   Age    city
0   21    Pune
1   22  Nagpur
2   24  unkown
3   22  Mumbai

**QUE.2)**

In [48]:
data = {
    "Name": [
        "Prachi", "Rahul", None, "Amit", "Rahul",
        None, "Rohan", "Kunal", "Pooja", None
    ],

    "Age": [
        21, None, 24, 25, None,
        28, 30, None, 22, 27
    ],

    "City": [
        "Pune", "Nagpur", None, "Mumbai", "Delhi",
        "Chennai", None, "Hyderabad", None, "Bangalore"
    ],

    "Salary": [
        25000, None, 30000, 28000, None,
        35000, 40000, None, 27000, 32000
    ],

    "Department": [
        "IT", "HR", None, "Finance", "IT",
        None, "Sales", "Marketing", None, "HR"
    ]
}

df = pandas.DataFrame(data)
print(df)

     Name   Age       City   Salary Department
0  Prachi  21.0       Pune  25000.0         IT
1   Rahul   NaN     Nagpur      NaN         HR
2    None  24.0       None  30000.0       None
3    Amit  25.0     Mumbai  28000.0    Finance
4   Rahul   NaN      Delhi      NaN         IT
5    None  28.0    Chennai  35000.0       None
6   Rohan  30.0       None  40000.0      Sales
7   Kunal   NaN  Hyderabad      NaN  Marketing
8   Pooja  22.0       None  27000.0       None
9    None  27.0  Bangalore  32000.0         HR

In [37]:
# 1. check the missing values
print(df.isnull())

    Name    Age   City  Salary  Department
0  False  False  False   False       False
1  False   True  False    True       False
2   True  False   True   False        True
3  False  False  False   False       False
4  False   True  False    True       False
5   True  False  False   False        True
6  False  False   True   False       False
7  False   True  False    True       False
8  False  False   True   False        True
9   True  False  False   False       False

In [38]:
# 2. Counts the Total missing values
print(df.isnull().sum().sum())

15

In [39]:
# 3. Counts the column wise missing values
print(df.isnull().sum())

Name          3
Age           3
City          3
Salary        3
Department    3
dtype: int64

In [40]:
# 4. Fill missing value in name with 'Unknown'
df['Name'].fillna('Unknown',inplace=True)
print(df)

      Name   Age       City   Salary Department
0   Prachi  21.0       Pune  25000.0         IT
1    Rahul   NaN     Nagpur      NaN         HR
2  Unknown  24.0       None  30000.0       None
3     Amit  25.0     Mumbai  28000.0    Finance
4    Rahul   NaN      Delhi      NaN         IT
5  Unknown  28.0    Chennai  35000.0       None
6    Rohan  30.0       None  40000.0      Sales
7    Kunal   NaN  Hyderabad      NaN  Marketing
8    Pooja  22.0       None  27000.0       None
9  Unknown  27.0  Bangalore  32000.0         HR

/tmp/ipykernel_4160/3063909084.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Name'].fillna('Unknown',inplace=True)

In [41]:
# 5. Fill missing values in Age using mean
df['Age']= df['Age'].fillna(df['Age'].mean())
print(df)

      Name        Age       City   Salary Department
0   Prachi  21.000000       Pune  25000.0         IT
1    Rahul  25.285714     Nagpur      NaN         HR
2  Unknown  24.000000       None  30000.0       None
3     Amit  25.000000     Mumbai  28000.0    Finance
4    Rahul  25.285714      Delhi      NaN         IT
5  Unknown  28.000000    Chennai  35000.0       None
6    Rohan  30.000000       None  40000.0      Sales
7    Kunal  25.285714  Hyderabad      NaN  Marketing
8    Pooja  22.000000       None  27000.0       None
9  Unknown  27.000000  Bangalore  32000.0         HR

In [42]:
# 6. Fill missing values in Salary using mean
df['Salary']= df['Salary'].fillna(df['Salary'].mean())
print(df)

      Name        Age       City   Salary Department
0   Prachi  21.000000       Pune  25000.0         IT
1    Rahul  25.285714     Nagpur  31000.0         HR
2  Unknown  24.000000       None  30000.0       None
3     Amit  25.000000     Mumbai  28000.0    Finance
4    Rahul  25.285714      Delhi  31000.0         IT
5  Unknown  28.000000    Chennai  35000.0       None
6    Rohan  30.000000       None  40000.0      Sales
7    Kunal  25.285714  Hyderabad  31000.0  Marketing
8    Pooja  22.000000       None  27000.0       None
9  Unknown  27.000000  Bangalore  32000.0         HR

In [43]:
# 7. Removes rows having Nan
res= df.dropna()
print(res)

      Name        Age       City   Salary Department
0   Prachi  21.000000       Pune  25000.0         IT
1    Rahul  25.285714     Nagpur  31000.0         HR
3     Amit  25.000000     Mumbai  28000.0    Finance
4    Rahul  25.285714      Delhi  31000.0         IT
7    Kunal  25.285714  Hyderabad  31000.0  Marketing
9  Unknown  27.000000  Bangalore  32000.0         HR

In [44]:
# 8. Remove columns having Nan
res = df.dropna(axis=1)  # depratment colums are delete bz conatins Nan value before rows deleting operation
print(res)

      Name        Age   Salary
0   Prachi  21.000000  25000.0
1    Rahul  25.285714  31000.0
2  Unknown  24.000000  30000.0
3     Amit  25.000000  28000.0
4    Rahul  25.285714  31000.0
5  Unknown  28.000000  35000.0
6    Rohan  30.000000  40000.0
7    Kunal  25.285714  31000.0
8    Pooja  22.000000  27000.0
9  Unknown  27.000000  32000.0

In [45]:
# 9. Convert Age columns into int type
df['Age']= df['Age'].astype(int)
print(df)

      Name  Age       City   Salary Department
0   Prachi   21       Pune  25000.0         IT
1    Rahul   25     Nagpur  31000.0         HR
2  Unknown   24       None  30000.0       None
3     Amit   25     Mumbai  28000.0    Finance
4    Rahul   25      Delhi  31000.0         IT
5  Unknown   28    Chennai  35000.0       None
6    Rohan   30       None  40000.0      Sales
7    Kunal   25  Hyderabad  31000.0  Marketing
8    Pooja   22       None  27000.0       None
9  Unknown   27  Bangalore  32000.0         HR

**QUE.3)**

In [65]:

data = {
    "Driver": [
        "Max Verstappen",
        "Lewis Hamilton",
        "Charles Leclerc",
        "Lewis Hamilton",
        "Fernando Alonso"
    ],

    "Team": [
        "Red Bull Racing",
        "Ferrari",
        "McLaren",
        "Ferrari",
        "Aston Martin"
    ],

    "Country": [
        "Netherlands",
        "United Kingdom",
        "Monaco",
        "United Kingdom",
        "Spain"
    ],

    "Championships": [
        4,
        7,
        0,
        7,
        2
    ],

    "Wins": [
        65,
        105,
        8,
        105,
        32
    ]
}

df = pandas.DataFrame(data)

print(df)

            Driver             Team         Country  Championships  Wins
0   Max Verstappen  Red Bull Racing     Netherlands              4    65
1   Lewis Hamilton          Ferrari  United Kingdom              7   105
2  Charles Leclerc          McLaren          Monaco              0     8
3   Lewis Hamilton          Ferrari  United Kingdom              7   105
4  Fernando Alonso     Aston Martin           Spain              2    32

**# Removes Duplicate value**

In [66]:
df.duplicated()   # when its show True -> their is duplicate value

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [67]:
# Delete Dupliacate Value
df=df.drop_duplicates()
print(df)

            Driver             Team         Country  Championships  Wins
0   Max Verstappen  Red Bull Racing     Netherlands              4    65
1   Lewis Hamilton          Ferrari  United Kingdom              7   105
2  Charles Leclerc          McLaren          Monaco              0     8
4  Fernando Alonso     Aston Martin           Spain              2    32

**# Renaming Columns**

In [69]:
df=pandas.read_pickle("mobilestock")
print(df.head(3))

   S.No    Brand        Model Name           Color  RAM (GB)  ROM (GB)  \
0     1  Samsung  Galaxy S24 Ultra  Titanium Black        12       256
1     2  Samsung       Galaxy S24+   Cobalt Violet        12       256
2     3  Samsung        Galaxy S24     Marble Gray         8       128

            Processor  Screen Size (inches)  Price (INR)
0  Snapdragon 8 Gen 3                   6.8       124999
1  Snapdragon 8 Gen 3                   6.7        99999
2  Snapdragon 8 Gen 3                   6.2        74999

In [77]:
df.rename(columns={"RAM (GB)":"RAM", "Screen Size (inches)": "Screen" },inplace=True)
print(df.head(5))

# print(df.columns)    it showing new values of columns

   S.No    Brand        Model Name            Color  RAM  ROM (GB)  \
0     1  Samsung  Galaxy S24 Ultra   Titanium Black   12       256
1     2  Samsung       Galaxy S24+    Cobalt Violet   12       256
2     3  Samsung        Galaxy S24      Marble Gray    8       128
3     4  Samsung        Galaxy A55     Awesome Navy    8       128
4     5  Samsung        Galaxy A35  Awesome Iceblue    6       128

            Processor  Screen  Price (INR)
0  Snapdragon 8 Gen 3     6.8       124999
1  Snapdragon 8 Gen 3     6.7        99999
2  Snapdragon 8 Gen 3     6.2        74999
3         Exynos 1480     6.6        38999
4         Exynos 1380     6.6        30999

**# Handling Strings**

In [100]:
df['Model Name'] = df['Model Name'].str.strip()
df['Brand'] = df['Brand'].str.upper()
df['Processor'] = df['Processor'].str.lower()

# First letter capital
df['Color'] = df['Color'].str.title()

# Length of string
df['Length'] = df['Model Name'].str.len()  # one extra col of len-> of model name

# Replace text
df['Brand'] = df['Brand'].str.replace('SAMSUNG', 'Vivo')


print(df)

    S.No     Brand          Model Name             Color  RAM  ROM (GB)  \
0      1      VIVO    Galaxy S24 Ultra    Titanium Black   12       256
1      2      VIVO         Galaxy S24+     Cobalt Violet   12       256
2      3      VIVO          Galaxy S24       Marble Gray    8       128
3      4      VIVO          Galaxy A55      Awesome Navy    8       128
4      5      VIVO          Galaxy A35   Awesome Iceblue    6       128
5      6      VIVO          Galaxy M55    Midnight Black    8       128
6      7      VIVO          Galaxy F55     Apricot Crush    8       256
7      8     APPLE   iPhone 15 Pro Max    Black Titanium    8       256
8      9     APPLE       iPhone 15 Pro    White Titanium    8       128
9     10     APPLE           iPhone 15              Pink    6       128
10    11     APPLE      iPhone 15 Plus            Yellow    6       128
11    12     APPLE           iPhone 14          Midnight    6       128
12    13     APPLE           iPhone 13         Starlight    4       128
13    14   ONEPLUS                  12       Silky Black   12       256
14    15   ONEPLUS                 12R         Iron Gray    8       128
15    16   ONEPLUS            Nord CE4       Dark Chrome    8       128
16    17   ONEPLUS              Nord 4  Mercurial Silver    8       256
17    18   ONEPLUS                Open      Emerald Dusk   16       512
18    19    XIAOMI            14 Ultra             White   16       512
19    20    XIAOMI                  14             Black   12       256
20    21    XIAOMI              13 Pro     Ceramic Black   12       256
21    22    XIAOMI  Redmi Note 13 Pro+      Fusion White   12       256
22    23    XIAOMI   Redmi Note 13 Pro       Scarlet Red    8       256
23    24    XIAOMI       Redmi Note 13      Arctic White    6       128
24    25    XIAOMI           Redmi 13C   Startrail Green    4       128
25    26      VIVO            X100 Pro    Asteroid Black   16       512
26    27      VIVO                X100    Startrail Blue   12       256
27    28      VIVO             V30 Pro     Peacock Green   12       256
28    29      VIVO                 V30         Aqua Blue    8       256
29    30      VIVO                Y200       Sequin Gold    8       128
30    31      OPPO         Find X7 Pro     Desert Silver   16       512
31    32      OPPO         Reno 12 Pro     Nebula Silver   12       256
32    33      OPPO             Reno 12      Astro Silver    8       256
33    34      OPPO              A3 Pro     Starry Purple    8       256
34    35      OPPO                 A60       Ripple Blue    8       128
35    36    REALME                GT 6      Fluid Silver   12       256
36    37    REALME               GT 6T      Fluid Silver    8       256
37    38    REALME        Narzo 70 Pro       Glass Green    8       128
38    39    REALME             12+ Pro   Navigator Beige   12       256
39    40    REALME                 C67       Dark Purple    8       128
40    41  MOTOROLA         Edge 50 Pro      Black Beauty   12       256
41    42  MOTOROLA      Edge 50 Fusion          Hot Pink    8       256
42    43  MOTOROLA                 G85       Olive Green    8       128
43    44  MOTOROLA                 G64         Ice Lilac    8       256
44    45     NOKIA                XR21             Black    6       128
45    46   NOTHING            Phone 2a             Black   12       256
46    47   NOTHING             Phone 2             White   12       256
47    48      IQOO                  12            Legend   16       256
48    49      IQOO           Neo 9 Pro         Fiery Red   12       256
49    50    GOOGLE         Pixel 8 Pro          Obsidian   12       128

                Processor  Screen  Price (INR)  Length
0      snapdragon 8 gen 3    6.80       124999      16
1      snapdragon 8 gen 3    6.70        99999      11
2      snapdragon 8 gen 3    6.20        74999      10
3             exynos 1480    6.60        38999      10
4             exynos 1380    6.60        30999      10
5      snapdragon 7 gen 1    6.70        27999      10
6      snapdragon 7 gen 1    6.70        26999      10
7           apple a17 pro    6.70       159900      17
8           apple a17 pro    6.10       134900      13
9        apple a16 bionic    6.10        79900       9
10       apple a16 bionic    6.70        89900      14
11       apple a15 bionic    6.10        69900       9
12       apple a15 bionic    6.10        54900       9
13     snapdragon 8 gen 3    6.82        64999       2
14     snapdragon 8 gen 1    6.78        42999       3
15    snapdragon 7s gen 2    6.67        24999       8
16    snapdragon 7+ gen 3    6.74        29999       6
17     snapdragon 8 gen 2    7.82       139999       4
18     snapdragon 8 gen 3    6.73        99999       8
19     snapdragon 8 gen 3    6.36        69999       2
20     snapdragon 8 gen 2    6.73        79999       6
21   dimensity 7200 ultra    6.67        31999      18
22    snapdragon 7s gen 2    6.67        26999      17
23         snapdragon 685    6.67        17999      13
24        dimensity 6100+    6.74        10999       9
25         dimensity 9300    6.78        89999       8
26         dimensity 9300    6.78        63999       4
27     snapdragon 7 gen 3    6.78        44999       7
28     snapdragon 7 gen 3    6.78        34999       3
29     snapdragon 4 gen 2    6.67        22999       4
30     snapdragon 8 gen 3    6.82        89999      11
31  dimensity 7300 energy    6.70        36999      11
32  dimensity 7300 energy    6.70        32999       7
33         dimensity 7050    6.70        24999       6
34         snapdragon 695    6.70        17999       3
35    snapdragon 8s gen 3    6.78        39999       4
36    snapdragon 7+ gen 3    6.67        30999       5
37         dimensity 7050    6.67        22999      12
38         dimensity 7050    6.67        27999       7
39         snapdragon 685    6.72        15999       3
40     snapdragon 7 gen 3    6.70        31999      11
41    snapdragon 7s gen 2    6.70        22999      14
42    snapdragon 6s gen 3    6.67        19999       3
43         dimensity 7025    6.50        15999       3
44         snapdragon 695    6.49        42999       4
45     dimensity 7200 pro    6.70        23999       8
46    snapdragon 8+ gen 1    6.70        44999       7
47     snapdragon 8 gen 3    6.78        52999       2
48     snapdragon 8 gen 2    6.78        36999       9
49       google tensor g3    6.70       106999      11

In [99]:
# Check contains
print(df['Brand'].str.contains('APPLE'))    # its show True

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
11     True
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: Brand, dtype: bool

In [103]:
# Starts with
print(df['Model Name'].str.startswith('iPhone'))

print(df.head(9))

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
11     True
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: Model Name, dtype: bool
   S.No  Brand         Model Name            Color  RAM  ROM (GB)  \
0     1   VIVO   Galaxy S24 Ultra   Titanium Black   12       256
1     2   VIVO        Galaxy S24+    Cobalt Violet   12       256
2     3   VIVO         Galaxy S24      Marble Gray    8       128
3     4   VIVO         Galaxy A55     Awesome Navy    8       128
4     5   VIVO         Galaxy A35  Awesome Iceblue    6       128
5     6   VIVO         Galaxy M55   Midnight Black    8       128
6     7   VIVO         Galaxy F55    Apricot Crush    8       256
7     8  APPLE  iPhone 15 Pro Max   Black Titanium    8       256
8     9  APPLE      iPhone 15 Pro   White Titanium    8       128

            Processor  Screen  Price (INR)  Length
0  snapdragon 8 gen 3     6.8       124999      16
1  snapdragon 8 gen 3     6.7        99999      11
2  snapdragon 8 gen 3     6.2        74999      10
3         exynos 1480     6.6        38999      10
4         exynos 1380     6.6        30999      10
5  snapdragon 7 gen 1     6.7        27999      10
6  snapdragon 7 gen 1     6.7        26999      10
7       apple a17 pro     6.7       159900      17
8       apple a17 pro     6.1       134900      13

In [104]:
# Ends with
print(df['Model Name'].str.endswith('Pro'))

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21    False
22     True
23    False
24    False
25     True
26    False
27     True
28    False
29    False
30     True
31     True
32    False
33     True
34    False
35    False
36    False
37     True
38     True
39    False
40     True
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48     True
49     True
Name: Model Name, dtype: bool

**# Handle inconsistent Values**

In [127]:

lst =[
    ['Mike','male'],
    ['will','m'],
    ['eleven','female'],
    ['max','f'],
    ['rutu','female']
]

df = pandas.DataFrame(lst)
print(df)

        0       1
0    Mike    male
1    will       m
2  eleven  female
3     max       f
4    rutu  female

In [130]:
# col[1 replaces with this Style

df['Gender'] = df['Gender'].replace({
    'm':'Male', 'M':'Male', 'male':'Male',
    'f':'Female', 'F':'Female', 'female':'Female'
})

print(df)

print('\nAfter changing First Letter in Capital of col[0] \n')

df['Name'] = df['Name'].str.title()
print(df)

# Giving column names
df.columns = ['Name', 'Gender']

# Giving row names (index)
df.index = [101, 102, 103, 104, 105]

       Name  Gender
101    Mike    Male
102    Will    Male
103  Eleven  Female
104     Max  Female
105    Rutu  Female

After changing First Letter in Capital of col[0]

       Name  Gender
101    Mike    Male
102    Will    Male
103  Eleven  Female
104     Max  Female
105    Rutu  Female

In [131]:
df=pandas.read_pickle("mobilestock")
print(df.head(3))

   S.No    Brand        Model Name           Color  RAM (GB)  ROM (GB)  \
0     1  Samsung  Galaxy S24 Ultra  Titanium Black        12       256
1     2  Samsung       Galaxy S24+   Cobalt Violet        12       256
2     3  Samsung        Galaxy S24     Marble Gray         8       128

            Processor  Screen Size (inches)  Price (INR)
0  Snapdragon 8 Gen 3                   6.8       124999
1  Snapdragon 8 Gen 3                   6.7        99999
2  Snapdragon 8 Gen 3                   6.2        74999

In [132]:
res=df[df['RAM (GB)']>10]
print(res.shape)

(21, 9)

**# Delete colum color and processor**

In [137]:
res=df.drop(columns=['Color','Processor','Screen Size (inches)'])
print(res)

    S.No     Brand          Model Name  RAM (GB)  ROM (GB)  Price (INR)
0      1   Samsung    Galaxy S24 Ultra        12       256       124999
1      2   Samsung         Galaxy S24+        12       256        99999
2      3   Samsung          Galaxy S24         8       128        74999
3      4   Samsung          Galaxy A55         8       128        38999
4      5   Samsung          Galaxy A35         6       128        30999
5      6   Samsung          Galaxy M55         8       128        27999
6      7   Samsung          Galaxy F55         8       256        26999
7      8     Apple   iPhone 15 Pro Max         8       256       159900
8      9     Apple       iPhone 15 Pro         8       128       134900
9     10     Apple           iPhone 15         6       128        79900
10    11     Apple      iPhone 15 Plus         6       128        89900
11    12     Apple           iPhone 14         6       128        69900
12    13     Apple           iPhone 13         4       128        54900
13    14   OnePlus                  12        12       256        64999
14    15   OnePlus                 12R         8       128        42999
15    16   OnePlus            Nord CE4         8       128        24999
16    17   OnePlus              Nord 4         8       256        29999
17    18   OnePlus                Open        16       512       139999
18    19    Xiaomi            14 Ultra        16       512        99999
19    20    Xiaomi                  14        12       256        69999
20    21    Xiaomi              13 Pro        12       256        79999
21    22    Xiaomi  Redmi Note 13 Pro+        12       256        31999
22    23    Xiaomi   Redmi Note 13 Pro         8       256        26999
23    24    Xiaomi       Redmi Note 13         6       128        17999
24    25    Xiaomi           Redmi 13C         4       128        10999
25    26      Vivo            X100 Pro        16       512        89999
26    27      Vivo                X100        12       256        63999
27    28      Vivo             V30 Pro        12       256        44999
28    29      Vivo                 V30         8       256        34999
29    30      Vivo                Y200         8       128        22999
30    31      OPPO         Find X7 Pro        16       512        89999
31    32      OPPO         Reno 12 Pro        12       256        36999
32    33      OPPO             Reno 12         8       256        32999
33    34      OPPO              A3 Pro         8       256        24999
34    35      OPPO                 A60         8       128        17999
35    36    Realme                GT 6        12       256        39999
36    37    Realme               GT 6T         8       256        30999
37    38    Realme        Narzo 70 Pro         8       128        22999
38    39    Realme             12+ Pro        12       256        27999
39    40    Realme                 C67         8       128        15999
40    41  Motorola         Edge 50 Pro        12       256        31999
41    42  Motorola      Edge 50 Fusion         8       256        22999
42    43  Motorola                 G85         8       128        19999
43    44  Motorola                 G64         8       256        15999
44    45     Nokia                XR21         6       128        42999
45    46   Nothing            Phone 2a        12       256        23999
46    47   Nothing             Phone 2        12       256        44999
47    48      iQOO                  12        16       256        52999
48    49      iQOO           Neo 9 Pro        12       256        36999
49    50    Google         Pixel 8 Pro        12       128       106999

**# Rest Index from 1 to so..on**

In [139]:
res=df[df['RAM (GB)']>10]
print(res.shape)

res.reset_index(drop=True,inplace=True)
print(res.head(4))

(21, 9)
   S.No    Brand        Model Name           Color  RAM (GB)  ROM (GB)  \
0     1  Samsung  Galaxy S24 Ultra  Titanium Black        12       256
1     2  Samsung       Galaxy S24+   Cobalt Violet        12       256
2    14  OnePlus                12     Silky Black        12       256
3    18  OnePlus              Open    Emerald Dusk        16       512

            Processor  Screen Size (inches)  Price (INR)
0  Snapdragon 8 Gen 3                  6.80       124999
1  Snapdragon 8 Gen 3                  6.70        99999
2  Snapdragon 8 Gen 3                  6.82        64999
3  Snapdragon 8 Gen 2                  7.82       139999

**# Final Verifaction**

In [140]:
print(df.isnull().sum().sum())
print(df.duplicated().sum())

0
0